import { useState } from "react";
import { motion } from "framer-motion";
import { useReveal } from "@/lib/hooks";
import { Lightbulb } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function InteractiveDemo() {
  const [ref, inView] = useReveal();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [ideaInput, setIdeaInput] = useState("A dashboard that visualizes personal spending habits");

  const handleGenerate = () => {
    setIsGenerating(true);
    
    // Simulate AI generation with a timeout
    setTimeout(() => {
      setIsGenerating(false);
      setIsGenerated(true);
    }, 1500);
  };

  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8 overflow-hidden relative">
      <div className="absolute top-1/2 left-0 -ml-40 w-80 h-80 rounded-full bg-gradient-to-r from-purple-600 to-blue-600 opacity-10 blur-3xl"></div>
      
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-16">
          <motion.h2
            ref={ref}
            initial={{ opacity: 0, y: 20 }}
            animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ duration: 0.8 }}
            className="text-3xl sm:text-4xl font-extrabold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent mb-4"
          >
            Experience The Flow
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ duration: 0.8, delay: 0.1 }}
            className="max-w-2xl mx-auto text-lg text-gray-600"
          >
            See how Noveloper transforms ideas into reality without code.
          </motion.p>
        </div>
        
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="bg-white rounded-xl shadow-lg overflow-hidden"
        >
          <div className="p-4 bg-gray-100 flex items-center">
            <div className="flex space-x-2">
              <div className="w-3 h-3 rounded-full bg-red-500"></div>
              <div className="w-3 h-3 rounded-full bg-yellow-500"></div>
              <div className="w-3 h-3 rounded-full bg-green-500"></div>
            </div>
            <div className="ml-4 text-sm text-gray-600 font-mono">noveloper-demo.app</div>
          </div>
          
          <div className="p-6 flex flex-col items-center text-center">
            <div className="w-full max-w-md">
              <div className="font-mono text-sm text-gray-500 mb-4">// Define your idea</div>
              <div className="flex mb-6">
                <Input
                  type="text"
                  placeholder="Describe your app idea..."
                  className="flex-grow px-4 py-3 rounded-l-md focus:ring-2 focus:ring-purple-600 text-base"
                  value={ideaInput}
                  onChange={(e) => setIdeaInput(e.target.value)}
                />
                <Button
                  onClick={handleGenerate}
                  className="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-4 py-2 rounded-r-md hover:opacity-90 transition duration-300"
                >
                  Generate
                </Button>
              </div>
              
              <div className="w-full min-h-[300px] bg-gray-50 rounded-lg p-6 flex items-center justify-center border border-gray-200 overflow-hidden">
                {isGenerating ? (
                  <div className="text-center">
                    <div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-purple-600 mb-4"></div>
                    <p>Generating your concept...</p>
                  </div>
                ) : isGenerated ? (
                  <div className="w-full">
                    <div className="mb-4 flex justify-between items-center">
                      <h3 className="font-bold text-lg">Personal Finance Dashboard</h3>
                      <div className="text-sm text-gray-500">Generated by Noveloper</div>
                    </div>
                    <div className="grid grid-cols-2 gap-4 mb-6">
                      <div className="bg-white p-4 rounded-lg shadow">
                        <div className="text-sm text-gray-500 mb-1">Monthly Overview</div>
                        <div className="font-bold text-2xl">$2,450</div>
                        <div className="h-4 w-full bg-gray-200 rounded-full mt-2">
                          <div className="h-4 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full" style={{ width: '65%' }}></div>
                        </div>
                      </div>
                      <div className="bg-white p-4 rounded-lg shadow">
                        <div className="text-sm text-gray-500 mb-1">Savings Goal</div>
                        <div className="font-bold text-2xl">$10,000</div>
                        <div className="h-4 w-full bg-gray-200 rounded-full mt-2">
                          <div className="h-4 bg-gradient-to-r from-purple-600 to-blue-600 rounded-full" style={{ width: '35%' }}></div>
                        </div>
                      </div>
                    </div>
                    <div className="bg-white p-4 rounded-lg shadow mb-4">
                      <div className="text-sm text-gray-500 mb-2">Spending Categories</div>
                      <div className="space-y-3">
                        <div>
                          <div className="flex justify-between mb-1">
                            <span>Housing</span>
                            <span>$1,200</span>
                          </div>
                          <div className="h-2 w-full bg-gray-200 rounded-full">
                            <div className="h-2 bg-blue-500 rounded-full" style={{ width: '40%' }}></div>
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between mb-1">
                            <span>Food</span>
                            <span>$450</span>
                          </div>
                          <div className="h-2 w-full bg-gray-200 rounded-full">
                            <div className="h-2 bg-green-500 rounded-full" style={{ width: '15%' }}></div>
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between mb-1">
                            <span>Entertainment</span>
                            <span>$350</span>
                          </div>
                          <div className="h-2 w-full bg-gray-200 rounded-full">
                            <div className="h-2 bg-purple-500 rounded-full" style={{ width: '12%' }}></div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="text-center text-sm text-gray-500">
                      This prototype was generated without writing code, using Noveloper's AI.
                    </div>
                  </div>
                ) : (
                  <div className="text-center text-gray-400">
                    <Lightbulb className="h-16 w-16 mx-auto mb-4 opacity-30" />
                    <p>Click "Generate" to see the magic happen.</p>
                    <p className="text-sm mt-2">Your idea will be transformed into a visual concept.</p>
                  </div>
                )}
              </div>
              
              <div className="mt-4 text-xs text-gray-500 italic">
                This is a simulated demo. In a real Noveloper environment, AI would generate a functional prototype based on your description.
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
