name: Deploy Development to Vercel

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel (Development)
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_m8M0nIxMJpfBMPEAvcQV2vtPzS2c/McSJvPZSCO"